# Tell Travis CI we're using PHP
language: php

# Currently checking only against latest PHP - PHPCompatibilityWP does linting for earlier versions
php:
  - 7.3

before_script:
- composer install

script: ./vendor/bin/phpcs -p cbox-openlab-core.php classes/ includes/ lib/ --standard=PHPCompatibilityWP --runtime-set testVersion 5.6- --extensions=php
